### ISSUE TITLE
Installation from MELPA doesn't work

### ISSUE THREAD

**Issue by gvol** [200ok-ch/counsel-jq#1]
I tried to install via MELPA.  I didn't previously have counsel installed, and it failed to install it.  It seems to depend on the ivy package, but on the swiper file which is (presumably) in the swiper package which was not installed automatically.  

On the other hand, the swiper package depends on ivy, so it seems that this should depend on swiper instead.  And perhaps the counsel package as well (or maybe the name is wrong)?

```
Compiling file /Users/iandrus/.emacs.d/elpa/counsel-jq-20191202.846/counsel-jq.el at Mon Dec  2 14:09:55 2019
Entering directory ‘/Users/iandrus/.emacs.d/elpa/counsel-jq-20191202.846/’
counsel-jq.el:12:1:Error: Cannot open load file: No such file or directory, swiper
```

**Comment by To1ne** [comment]
`ivy`, `swiper`, and `counsel` live in the same codebase: https://github.com/abo-abo/swiper. It's sometimes confusing.

Loading `swiper` was changed not so long ago: https://github.com/200ok-ch/counsel-jq/commit/c940636fe55f26d35d9d2d23adcb6f931a6df5e0. Although I don't really understand why this change was made. I would suggest to revert it.

**Comment by munen** [comment]
Thank you for the issue, @gvol and thank you for the comment @To1ne :pray: 

I added `swiper` as a direct dependency. After the next build of Melpa packages, installation should work without pre-installed Swiper.

I apologize for the mistake. I removed it due to a linter problem that said swiper wasn't installable. However, after a package refresh, it becomes installable..

Thank you again and enjoy using counsel-jq(;
